
package eventsystem.Ventanas.JInternas;

import eventsystem.Ventanas.Login;
import java.awt.Color;
import java.sql.ResultSet;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;


public class GruposCrear extends javax.swing.JInternalFrame {

    
     
    DefaultListModel ListaM = new DefaultListModel();
     DefaultListModel ListaE = new DefaultListModel();
     DefaultListModel ListaOM = new DefaultListModel(); //Es una lista oculta para guardar los id de las personas
     
    Vector<String> OcultosMiembros;
  
    public GruposCrear() {
        initComponents();
        
        ListaMiembros.setModel(ListaM);
     
        ListaEnvios.setModel(ListaE);
        OcultosMiembros = new Vector<String>(); //Este vector guardar todos los id seleccionados de los miembros-
        

        
        
        limpiar();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TxtNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        BtnGuardar1 = new javax.swing.JButton();
        BtnGuardar2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaMiembros = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaEnvios = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        BtnGuardar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Nombre del grupo:");

        BtnGuardar1.setText("Limpiar todo");
        BtnGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardar1ActionPerformed(evt);
            }
        });

        BtnGuardar2.setText("Cerrar");
        BtnGuardar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardar2ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jScrollPane1.setViewportView(ListaMiembros);

        jScrollPane2.setViewportView(ListaEnvios);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText("Lista de miembros");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setText("Agregar al grupo:");

        jButton1.setText("Seleccionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        BtnGuardar.setText("Crear");
        BtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(89, 89, 89))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(BtnGuardar)))
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtnGuardar1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnGuardar2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnGuardar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnGuardar2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed

        if(TxtNombre.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Debe indicar un nombre para el grupo","Error",JOptionPane.ERROR_MESSAGE);
            TxtNombre.grabFocus();
        }else{

             if(ListaEnvios.getModel().getSize() > 0){

         
            
            try{

                Herramientas.Procedimientos.CrearGrupo(TxtNombre.getText(), Login.GetCodUsuario());
                
                
                   try{
                    
                   
                    //Para buscar el codigo del ultimo grupo
                    ResultSet res = Herramientas.Utilidades.Consulta("Select Max(CodGrupo) as Resultado from Grupos where CodUsuario='" + Login.GetCodUsuario() + "'");

                    res.next();
                    String CodGrupo = res.getString("Resultado");

                    for (String CodigoMiembro : OcultosMiembros) {
                        Herramientas.Procedimientos.InsertarGruposVsMiembros(CodGrupo, CodigoMiembro);

                    }

               
                }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Error: "+e.getMessage());
                }
                   
                JOptionPane.showMessageDialog(null,"Se ha creado el grupo correctamente.","Aviso",JOptionPane.INFORMATION_MESSAGE);
                limpiar();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Error al conectar con la BD "+e.getMessage());
            }
            
             }else{
                 JOptionPane.showMessageDialog(null, "Debe de seleccionar al menos un miembro para crear el grupo.","Error",JOptionPane.ERROR_MESSAGE);
             }

        }

    }//GEN-LAST:event_BtnGuardarActionPerformed

     public void limpiar(){
          
      
        TxtNombre.setText("");
    
       ListaEnvios.setBackground(Color.decode("#FFFFFF"));
        TxtNombre.grabFocus();
        try{
         
         
         CargarPalabras();
         
         
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error: "+e.getMessage());
        }
        
    }
     
     public void CargarPalabras(){
         
         try {
             
              ListaE.removeAllElements();
            ListaM.removeAllElements();
            ListaOM.removeAllElements();
          
            OcultosMiembros.clear();

             ResultSet res = Herramientas.Utilidades.Consulta("Select * from Miembros where CodUsuario='" + Login.GetCodUsuario() + "'");
             while (res.next()) {

                 ListaM.addElement(res.getString("Nombre") + " " + res.getString("Apellido"));
                // JOptionPane.showMessageDialog(null, "CodMiem: "+res.getString("CodMiembro"));
                 
                 ListaOM.addElement(res.getString("CodMiembro"));
             }

//             
         } catch (Exception e) {
             JOptionPane.showMessageDialog(null, "Error al conectar con la BD " + e.getMessage());
         }
    }
    
    private void BtnGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardar1ActionPerformed
       limpiar();
    }//GEN-LAST:event_BtnGuardar1ActionPerformed

    private void BtnGuardar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardar2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_BtnGuardar2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
          try{
             
              
              
              
                       int c = ListaMiembros.getSelectedIndex();

              String elemento = (String) ListaMiembros.getSelectedValue();
              ListaE.addElement(elemento);

              OcultosMiembros.add(ListaOM.getElementAt(c).toString());
               ListaEnvios.setBackground(Color.decode("#819FF7"));

              ListaOM.remove(c);
              ListaM.remove(c);
               

               
        }catch(Exception e){
             
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         try{
     
            ListaE.removeAllElements();
            ListaM.removeAllElements();
            ListaEnvios.setBackground(Color.decode("#FFFFFF"));
             OcultosMiembros.clear();
            
         CargarPalabras();
        }catch(Exception e){
          
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JButton BtnGuardar1;
    private javax.swing.JButton BtnGuardar2;
    private javax.swing.JList<String> ListaEnvios;
    private javax.swing.JList<String> ListaMiembros;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
